### ISSUE TITLE
week1 konular

### ISSUE THREAD

**Issue by Pamir** [mlhylmz81/Python#1]
1. Repo değişmesi gerekli Repo ismi python olacak içinde klasör olarak week1 olacak
2. Hesapamayı daha optimize yazabilirsin

**Comment by Pamir** [comment]
1. Time.sleep gereksiz
2. Belirli sayıda dönüş (1000) kere bunun yerine while True: de işlem * + - yerine exit gelirse döngüden çıksın
3. her işlemde input almışsın gerek yok en tepeye taşıyabilirsin while'ın altına
4 os.system cls  gerek yok
5. try / catch yerine 2. eleman 0 mı diye kontrol etmen daha mantıklı try / 
6. döngüden çıktıktan sonra x+1 demişsin gereksiz
7. her defa print sonuç demişsin işlemini yap daha sonra en son print sonuç de aynı kodu sürekli yazmışsın
8. işlem tipleri 1/2/3/4 değil + - * / olacak

**Comment by mlhylmz81** [comment]
Sorunları düzelttim sanırım hocam tekrar bakabilir misiniz?

**Comment by Pamir** [comment]
issue yu kapatabilirsin benim repo'da notunu verdim

**Comment by mlhylmz81** [comment]
Teşekkür ederim hocam iyi geceler

3 Mar 2018 23:40 tarihinde "Pamir" <notifications@github.com> yazdı:
